#!/usr/bin/env node

repl = require('repl');

find_peptide = function(agi,seq) {
    (new MASCP.TairReader()).retrieve(agi,function(err) {
        if (err) {
            return;
        }
        console.log(this.result.getSequence().indexOf(seq));
    })
}

find_sequence = function(agi) {
    (new MASCP.TairReader()).retrieve(agi,function(err) {
        if (err) {
            return;
        }
        console.log(this.result.getSequence());
    })    
}

MASCP = require('./dist/js/maschup.services.min.js');
MASCP.events.once('ready',function() {
    repl.start("MASCP tools> ");
});